version: '3.5'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab-22-srikanth-iyengar.cloud.okteto.net
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8822:22"
    networks:
      - gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'adminadmin'
